[package]
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]
edition = "2018"
name = "rustc_testrunner"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.3.1"
rayon = "1.3.0"
walkdir = "2.3.1"
