[package]
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]
edition = "2018"
name = "rustc_testrunner"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.3"
itertools = "0.9"
pico-args = "0.3.1"
rayon = "1.3.0"
tempfile = "3.1"
walkdir = "2.3.1"
