[package]
name = "rustc_testrunner"
version = "0.1.0"
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
rayon = "1.3.0"

[profile.release]
codegen-units=1
lto=true
incremental=false
